### ISSUE TITLE
Coverage check support for pull_request

### ISSUE THREAD

**Issue by gforti** [devmasx/coverage-check-action#11]
**Description**
As a Developer
I want to be able to configure coverage-check-action on a pull_request
So that the action can run the check when a pull request is opened and updated.
 
**Acceptance Criteria**

Scenario 1: Github action yml file is configured for `pull_request`
Given that I have configured my github action pull request
And I have coverage-check-action configured
When a developer creates a pull request
Then the github action will execute
And coerage-check-action will run the coverage report
 
**SCOPE CLARIFICATION**
Not all trigger events need to be accounted for, just `pull_request`

**Additional context**
Here is a sample file that can be used to test
```yml
name: Coverage Check PR

on:
  pull_request:
    branches-ignore: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Run Test
      run: npm test

    - name: Coverage Check
      uses: devmasx/coverage-check-action@v1.2.0
      with:
        type: lcov
        result_path: ./test/unit/coverage/lcov.info
        min_coverage: 85
        token: ${{ github.token }}
```
